[project]
name = "measnode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=2.2",
    "pynvim>=0.5.2",
    "pyright>=1.1.401",
    "ruff>=0.11.10",
]
